-- MySQL Script generated by MySQL Workbench
-- Mon Feb 13 16:25:59 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema blogs_schema
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema blogs_schema
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `blogs_schema` DEFAULT CHARACTER SET utf8 ;
USE `blogs_schema` ;

-- -----------------------------------------------------
-- Table `blogs_schema`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blogs_schema`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(255) NULL,
  `last_name` VARCHAR(255) NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `created_at` DATETIME NULL DEFAULT NOW(),
  `updated_at` DATETIME NULL DEFAULT NOW() UPDATED AT NOW(),
  PRIMARY KEY (`id`))
ENGINE = InnoDB
KEY_BLOCK_SIZE = 1;


-- -----------------------------------------------------
-- Table `blogs_schema`.`blogs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blogs_schema`.`blogs` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `blogs_schema`.`posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blogs_schema`.`posts` (
  `id` INT NOT NULL,
  `title` VARCHAR(255) NULL,
  `content` TEXT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `blog_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_posts_blogs1_idx` (`blog_id` ASC) VISIBLE,
  CONSTRAINT `fk_posts_blogs1`
    FOREIGN KEY (`blog_id`)
    REFERENCES `blogs_schema`.`blogs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `blogs_schema`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blogs_schema`.`comments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NULL,
  `content` TEXT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `user_id` INT NOT NULL,
  `post_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_comments_users_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_comments_posts1_idx` (`post_id` ASC) VISIBLE,
  CONSTRAINT `fk_comments_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `blogs_schema`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comments_posts1`
    FOREIGN KEY (`post_id`)
    REFERENCES `blogs_schema`.`posts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `blogs_schema`.`files`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blogs_schema`.`files` (
  `id` INT NOT NULL,
  `file_path` VARCHAR(255) NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `post_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_files_posts1_idx` (`post_id` ASC) VISIBLE,
  CONSTRAINT `fk_files_posts1`
    FOREIGN KEY (`post_id`)
    REFERENCES `blogs_schema`.`posts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `blogs_schema`.`admins`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blogs_schema`.`admins` (
  `create_time` DATETIME NULL DEFAULT NOW(),
  `update_time` DATETIME NULL DEFAULT NOW() ON UPDATE NOW(),
  `users_id` INT NOT NULL,
  `blogs_id` INT NOT NULL,
  INDEX `fk_admins_users1_idx` (`users_id` ASC) VISIBLE,
  INDEX `fk_admins_blogs1_idx` (`blogs_id` ASC) VISIBLE,
  CONSTRAINT `fk_admins_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `blogs_schema`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_admins_blogs1`
    FOREIGN KEY (`blogs_id`)
    REFERENCES `blogs_schema`.`blogs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `blogs_schema`.`users_has_blogs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blogs_schema`.`users_has_blogs` (
  `users_id` INT NOT NULL,
  `blogs_id` INT NOT NULL,
  PRIMARY KEY (`users_id`, `blogs_id`),
  INDEX `fk_users_has_blogs_blogs1_idx` (`blogs_id` ASC) VISIBLE,
  INDEX `fk_users_has_blogs_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_has_blogs_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `blogs_schema`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_blogs_blogs1`
    FOREIGN KEY (`blogs_id`)
    REFERENCES `blogs_schema`.`blogs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
